#!/bin/bash

cd ~

export EDITOR=helix
export XCURSOR_SIZE=24
export BROWSER="/usr/bin/firefox"

# export _JAVA_AWT_WM_NONREPARENTING=1
# export CLUTTER_BACKEND=wayland
# export XDG_SESSION_TYPE=wayland
# export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
# export MOZ_ENABLE_WAYLAND=1
# export GBM_BACKEND=nvidia-drm
# export __GLX_VENDOR_LIBRARY_NAME=nvidia
# export WLR_NO_HARDWARE_CURSORS=1
# export WLR_BACKEND=vulkan
# export QT_QPA_PLATFORM=wayland
# export GDK_BACKEND=wayland

# export QT_QPA_PLATFORMTHEME="qtct"
export XDG_CURRENT_DESKTOP=Hyprland
# export XDG_SESSION_DESKTOP=sway
# export XDG_CURRENT_SESSION_TYPE=wayland


exec Hyprland
