theme = "rasmus"

[editor]
line-number = "relative"
bufferline = "always"
cursorline = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
